### PR TITLE
fix(init): avoid accidentally overriding user-defined aliases

### PR DESCRIPTION
**Pull request by typesanitizer**
Draft fix for #219.

What works: if you put an alias in `~/.gitconfig`, then it gets picked over aliases defined by `git-branchless`. So it does solve the immediate problem. This is verified by a new test case.

What doesn't work:
1. If `HOME` is unset, this will give an error. Is it safe to assume that `HOME` will always be set on Unixes?
2. Any other config files, such as `$XDG_CONFIG_HOME/git/config` get lower priority even if they are included later, you were right about that. It's not clear to me why `~` gets special treatment, but it does. 

    This is also why I initially got excited by the solution in the issue discussion, because I accidentally ended up trying the thing that worked manually first. 😬

Because of 1., a bunch of test cases start failing (HOME is unset), and I will probably need to add a special case for Windows. That said, given the drawbacks of this approach, I'm not sure if you want to go with this now. If you're fine with the approach, I'm happy to fix the tests + add the Windows special case. The other alternative is I can change the implementation strategy if you have a better idea on how all cases could be handled at once.

### CODE REVIEW

**Comment by arxanas** [comment]
If you add an include for `~/.gitconfig`, what happens to multivar configuration (like `core.gitproxy`)? Do they appear twice when listed with `git config --get-all`? If so, then I think we shouldn't re-include an already-applied configuration file, or it may unexpectedly change the behavior of something.

My suggested workaround is to figure out whether an alias of the given name already exists and was not defined by `git-branchless`, and if so, to skip installing that alias and delete the existing `git-branchless` alias, if any. It's not ideal, but it's something 🤷

**Review by arxanas — CHANGES_REQUESTED** [review]
Putting back in your queue.

**Comment by typesanitizer** [comment]
> If you add an include for ~/.gitconfig, what happens to multivar configuration (like core.gitproxy)? Do they appear twice when listed with git config --get-all? If so, then I think we shouldn't re-include an already-applied configuration file, or it may unexpectedly change the behavior of something.

Yep, it does show up twice.

> My suggested workaround is to figure out whether an alias of the given name already exists and was not defined by git-branchless, and if so, to skip installing that alias and delete the existing git-branchless alias, if any. It's not ideal, but it's something 🤷

Sounds like a reasonable compromise. I will get to this in a day or two.

**Comment by arxanas** [comment]
Closing for now, re-open if you want a re-review.

**Pull request closed without merging**
