### PR TITLE
refactor(dag): `CommitSet::from_iter()` -> `collect::<CommitSet>()`

### PR DESCRIPTION
**Pull request by claytonrcarter**
> Oops, I wrote CommitSet::from_iter(foo.collect()) but it should be just foo.collect(). Anyways, you can leave this as is, and I'll update this site and the other uses in the codebase to use .collect() later.

Is this what you had in mind over at https://github.com/arxanas/git-branchless/pull/366#discussion_r858156321?

Out of curiosity, do you generally prefer `let ... : CommitSet = ... .collect()` or `let ... = ... collect::<CommitSet>()`? Or does it depend on the context? My understanding ATM is that they're roughly equivalent ways of nudging the compiler towards the desired type, right?

### CODE REVIEW

**Comment by arxanas** [comment]
Thanks for cleaning this up!

> My understanding ATM is that they're roughly equivalent ways of nudging the compiler towards the desired type, right?

Yep, they're pretty much the same. Generally, I prefer `let x: CommitSet = (...).collect();` just because there's less line noise (as `::<>` can be a bit hard to read). I would say that Rust is actually missing the relevant feature, which is the ability to annotate the type of an arbitrary expression, and not just a pattern binding. Using the same `:` syntax, it might hypothetically look like this:

```
let x = foo
    .iter()
    .collect(): CommitSet;
```

I would probably prefer to do it that way if the feature existed.

**Comment by martinvonz** [comment]
> I would say that Rust is actually missing the relevant feature, which is the ability to annotate the type of an arbitrary expression, and not just a pattern binding. Using the same `:` syntax, it might hypothetically look like this:
> 
> ```
> let x = foo
>     .iter()
>     .collect(): CommitSet;
> ```
> 
> I would probably prefer to do it that way if the feature existed.

It's might be less hypothetical than you think: https://github.com/rust-lang/rust/issues/23416. At least I think that feature will allow you to write what you wanted.

**Comment by arxanas** [comment]
@martinvonz I knew the feature was in in RFC (after all, OCaml has it), but given that it's been 7+ years, I don't have any hope for it coming out anytime soon 😅.

**Comment by martinvonz** [comment]
> @martinvonz I knew the feature was in in RFC (after all, OCaml has it), but given that it's been 7+ years, I don't have any hope for it coming out anytime soon 😅.

Wow, I didn't realize it had been there for that long (or even very long at all)

**Pull request merged**
