### PR TITLE
Populate DAG during initialization

### PR DESCRIPTION
**Pull request by melko**
This addresses #308 calling the open_and_sync function at initialization.

### CODE REVIEW

**Comment by arxanas** [comment]
Thanks! For some reason, the CI jobs didn't run. I pushed another commit to run `cargo fmt` and re-run the CI jobs. If it works out, then I'll squash the commits together and merge.

**Review by arxanas — CHANGES_REQUESTED** [review]
It looks like a test is failing because it can't find the main branch. Perhaps, because it was just configured above, the appropriate configuration is not yet reflected in the current `repo` object? If so, you could reinitialize it from the repository and use that to sync the DAG.

**Comment by melko** [comment]
I think the problem is that in a fresh repo the master branch is created at the first commit, so it does not exist yet when `git branchless init` is run in that test.
You can get the same error by doing something like this:
```
git init
git branchless init
git sl
```

**Comment by melko** [comment]
A possible solution could be to not forward the Result<> from the `open_and_sync` called inside `init`,  so that if it fails the behavior should be the old one, something like this:
(not sure if a closure is the most ideomatic way to handle this, let me know)
```rust
    let _ = || -> eyre::Result<()> {
        let conn = repo.get_db_conn()?;
        let event_log_db = EventLogDb::new(&conn)?;
        let references_snapshot = repo.get_references_snapshot()?;
        let event_replayer = EventReplayer::from_event_log_db(effects, &repo, &event_log_db)?;
        let event_cursor = event_replayer.make_default_cursor();
        Dag::open_and_sync(
            effects,
            &repo,
            &event_replayer,
            event_cursor,
            &references_snapshot)?;
        Ok(())
    }();
```
what do you think about this?

**Comment by arxanas** [comment]
> I think the problem is that in a fresh repo the master branch is created at the first commit, so it does not exist yet when git branchless init is run in that test.

Actually, I think in this case it's fine to change the requirements for `git branchless init` and mandate that the main branch be created before invoking. Then we can just update the test to match. I wasn't able to push my change directly to your branch, so instead I opened https://github.com/arxanas/git-branchless/pull/686. Thanks for investigating this!

**Comment by melko** [comment]
Agreed, requiring the main branch to exist seems reasonable.
I fear you couldn't push it here because in the meanwhile I amended my PR to try the other solution, sorry.

I guess this PR can be closed then?

**Comment by arxanas** [comment]
@melko it turns out there are a few other cases which don't work well, as per the failing tests in PR #686. For example, `git record` might plausibly be used to *create* the first commit on the main branch (and therefore the main branch itself), so we don't want to require that the main branch exist before then. I ended up returning to your approach, but instead using `if let Ok(_) = ... {}` to handle the possible error case.

**Comment by arxanas** [comment]
Merged https://github.com/arxanas/git-branchless/pull/686, thanks again 😄.

**Pull request closed without merging**
