### PR TITLE
build: run `cargo update`

### PR DESCRIPTION
**Pull request by arxanas**

### CODE REVIEW

**Comment by arxanas** [comment]
@hmenke do you know how to update the Nix build to require Rust 1.16.0?

**Comment by hmenke** [comment]
I've bumped the nixpkgs version to one that includes Rust 1.61 (even by default).

**Comment by hmenke** [comment]
Built successfully on my local machine.

**Comment by hmenke** [comment]
Oops. Your force-push remove my commit from this PR.

**Comment by arxanas** [comment]
@hmenke thanks! I ended up finding a way to avoid raising the MSRV, but could you open that update to the lock file as a separate PR?

**Pull request merged**
