### PR TITLE
fix(git): simplify and generalise "symlinked `.git` directory" check

### PR DESCRIPTION
**Pull request by mlcui-google**
This handles `repo`-managed working copies, and should be generic enough to handle most other cases (unless the symlink points to a child of an ancestor).

### CODE REVIEW

**Comment by mlcui-google** [comment]
I haven't seen any false positives with this, including the case if the root of the working tree is a symlink.

See #900 for the PR that implemented the original check.

**Comment by mlcui-google** [comment]
DO NOT SUBMIT THIS PR until I have tested this with Git worktrees. I have a suspicion that this will result in incorrect behaviour with them...

**Comment by mlcui-google** [comment]
I just tested it with a worktree and it seems to work fine. Apologies for the false alarm - I haven't used worktrees before, so I wasn't sure about how things are handled in them...

**Review by arxanas — APPROVED** [review]
Looks good to me, thanks! I've added you as a collaborator on the repository so you can land this at your leisure.

**Comment by mlcui-google** [comment]
Thanks!

This PR feels a bit risky, but from my (limited) testing it should be okay. I'll keep an eye out for any issues relating to this.

**Pull request merged**
