### PR TITLE
cleanup(bug_report): remove unnecessary detail from a match expression

### PR DESCRIPTION
**Pull request by martinvonz**

### CODE REVIEW

**Comment by arxanas** [comment]
This is actually intentional! The idea is that if I add any new event types or fields, then I'll be forced to audit this use-site to evaluate whether it should be redacted. It could certainly use a comment, though :)

**Comment by martinvonz** [comment]
> This is actually intentional! The idea is that if I add any new event types or fields, then I'll be forced to audit this use-site to evaluate whether it should be redacted. It could certainly use a comment, though :)

Oh! I looked at the code in the PR that introduced it and couldn't figure out what the point was, but it makes sense that you want to be extra careful about it. I can repurpose this PR to be about adding a comment.

**Comment by martinvonz** [comment]
> I can repurpose this PR to be about adding a comment.

Done.

**Comment by arxanas** [comment]
Thanks for the quick adjustment!

**Pull request merged**
